// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrGJoOaPmmbKWB98Csw_YxqGiDNuXRs6s',
    appId: '1:314127095947:web:936dc8a0fdd488c8519c8e',
    messagingSenderId: '314127095947',
    projectId: 'mbbs-4f889',
    authDomain: 'mbbs-4f889.firebaseapp.com',
    storageBucket: 'mbbs-4f889.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1iGl0jeCLmWxWqapxR4C0dx5RmreuUQ',
    appId: '1:314127095947:android:be378e39bacfaf98519c8e',
    messagingSenderId: '314127095947',
    projectId: 'mbbs-4f889',
    storageBucket: 'mbbs-4f889.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWq7HQDyqY3fW05PWExmM4ut_wxoMwkSU',
    appId: '1:314127095947:ios:f614e2915a73eb3b519c8e',
    messagingSenderId: '314127095947',
    projectId: 'mbbs-4f889',
    storageBucket: 'mbbs-4f889.appspot.com',
    iosClientId: '314127095947-qiigiomjg4dkkumomqpgmk75e22uje5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWq7HQDyqY3fW05PWExmM4ut_wxoMwkSU',
    appId: '1:314127095947:ios:f614e2915a73eb3b519c8e',
    messagingSenderId: '314127095947',
    projectId: 'mbbs-4f889',
    storageBucket: 'mbbs-4f889.appspot.com',
    iosClientId: '314127095947-qiigiomjg4dkkumomqpgmk75e22uje5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.blood',
  );
}
